### ISSUE TITLE
How to access the API after running docker

### ISSUE THREAD

**Issue by agoel00** [sparrow-platform/disease-diagnostics-engine#1]
I followed the instructions on README and ran the docker container. But I cannot access the API at localhost:5000 

How do I access the chatbot?

**Comment by agoel00** [comment]
I was able to resolve the issue by changing the PORT inside the docker container. Thanks

**Comment by JayLohokare** [comment]
@agoel00 Correct - the port number should resolve this issue. 
Also, this repo is NOT a chatbot repo, but rather a backend API which a chatbot can interact with.
If you have any other questions, feel free to connect - jaylohokare@gmail.com

**Comment by JayLohokare** [comment]
@agoel00 Updated README with API request/response structure and examples

**Comment by agoel00** [comment]
Thanks for the quick update and resolution. 

Also, just like the similar symptoms function can I retrieve similar diseases to a specific disease given its CUID?

**Comment by agoel00** [comment]
Thanks for the quick update and resolution.

Also, just like the similar symptoms function can I retrieve similar
diseases to a specific disease given its CUID?

**Comment by JayLohokare** [comment]
No, but this can be done pretty easily - /predict endpoint gives you list of symptoms. Use these symptoms to find other relevant diseases

**Comment by agoel00** [comment]
That sounds like a cool method to try out. I'll try to write a method for computing similar diseases. Thanks.

**Comment by m-root** [comment]
Cannot pull the project from docker, so I had to install it on my local machine.

**Comment by m-root** [comment]
So after installing it I am unable to access it through port :5000. How can I go about.

**Comment by m-root** [comment]
@JayLohokare whenever I try installing while using docker, I get this error

`Using default tag: latest
Error response from daemon: manifest for jaylohokare/diseases-predictor:latest not found: manifest unknown: manifest unknown`

What might be the issue since that's what's leading me to do do a direct install. Even beside that while trying to install it inside docker, I'm getting an error. Kindly assist.

**Comment by JayLohokare** [comment]
@m-root I ran the following command, and the API was live on localhost
```
docker run -d -p 5000:5000 jaylohokare/diseases-predictor:0.5
```
Adding this command to README
